/content/documents/lks/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 304d7c99-36c0-498e-98e7-1b5f20c5bdf1
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: e79b221d-68ea-4866-9186-0cb46c67baf9
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: 3f76d453-f553-4b6d-9295-cfb9d58216ff
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: c70f0fc6-dfd4-40fb-87e0-b2faef6db1b9
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 2d52e4ae-3e2b-49e4-ad6d-52ddbbf45459
    hippotranslation:locale: en
