/content/documents/lks/training-programmes-pages:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c5992e29-6f86-4a1f-87d6-7a1eca87fa4e
  hippo:name: Training Programmes Pages
  hippostd:foldertype: [new-training-programmepage-folder, new-training-programmepage-document]
  hippotranslation:id: ce2452ee-f974-429a-8e3a-8413868fae36
  hippotranslation:locale: en
