definitions:
  config:
    /hst:hst/hst:configurations/common/hst:prototypepages/training-programme-page:
      jcr:primaryType: hst:component
      jcr:mixinTypes: ['hst:prototypemeta']
      hst:displayname: Training Programme Page
      hst:primarycontainer: main
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:containercomponent
        hippo:identifier: cafebabe-cafe-babe-cafe-babecafebabe
        hst:label: Training Programme Page Main
        hst:xtype: hst.vbox
      /header:
        jcr:primaryType: hst:component
        /top:
          jcr:primaryType: hst:component
          /multi-org-logo:
            jcr:primaryType: hst:containercomponent
            hippo:identifier: f2a42c7a-42e2-45a0-bd69-a31516459acf
            hst:label: Multi org logo
            hst:xtype: hst.vbox
