/content/documents/quality/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 115b3593-04fc-4165-aee7-461de6c9b7f2
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: 0289cecc-e167-49b5-85dc-17124252ee73
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: a57e1aef-200f-4743-b3fe-35b4fb5a6395
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 4c4807a6-8990-4d50-aa7d-a8b9ab673d9d
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 033e4a39-3ffc-4d4d-9e29-010b98701b8b
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 15d639dd-910a-4e0f-b608-be4c036b7258
    hippotranslation:locale: en
