/hippo:configuration/hippo:groups/{{ channelId }}-editor:
  jcr:primaryType: hipposys:group
  hipposys:members: []
  hipposys:securityprovider: internal
  hipposys:userroles: [xm.cms.user, xm.content.user, xm.channel.user, xm.channel.webmaster, xm.dashboard.user]