/hippo:configuration/hippo:groups/{{ channelId }}-viewer:
  jcr:primaryType: hipposys:group
  hipposys:members: []
  hipposys:securityprovider: internal
  hipposys:userroles: [xm.cms.user, xm.content.user]