/content/documents/medical/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c384ab99-2be0-453a-88a5-86db286b2b74
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: 72ecc7ac-16c3-4da0-9986-8fbff14a1c8a
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 45cca752-0ee0-41b7-9818-2abf8c53096b
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 74696ee7-9164-4b01-b6ee-394d83e5fab9
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 60026b30-b4ea-435b-a78c-668ca65c85e3
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: fc0d3f45-0549-47a0-bd73-a44f23e7200c
    hippotranslation:locale: en
