/content/documents/administration/valuelists/training-topic:
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
  jcr:uuid: 5d18f7e3-a0ff-4091-93c0-8e196072865c
  hippo:name: TrainingTopic
  /training-topic:
    jcr:primaryType: selection:valuelist
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
    jcr:uuid: d732b174-c6ac-403a-8010-d739ee9441df
    hippo:availability: [live, preview]
    hippotranslation:id: cc2ab086-19da-45b9-b6c5-e9eefb86462b
    hippotranslation:locale: inherited - from query
    /selection:listitem[1]:
      jcr:primaryType: selection:listitem
      selection:key: antimicrobial-resistance
      selection:label: Antimicrobial resistance
    /selection:listitem[2]:
      jcr:primaryType: selection:listitem
      selection:key: cancer-and-diagnostics
      selection:label: Cancer and diagnostics
    /selection:listitem[3]:
      jcr:primaryType: selection:listitem
      selection:key: children-and-young-people
      selection:label: Children and young people
    /selection:listitem[4]:
      jcr:primaryType: selection:listitem
      selection:key: community-care
      selection:label: Community care
    /selection:listitem[5]:
      jcr:primaryType: selection:listitem
      selection:key: cosmetic-procedures
      selection:label: Cosmetic procedures
    /selection:listitem[6]:
      jcr:primaryType: selection:listitem
      selection:key: covid-19
      selection:label: Covid-19
    /selection:listitem[7]:
      jcr:primaryType: selection:listitem
      selection:key: critical-care
      selection:label: Critical care
    /selection:listitem[8]:
      jcr:primaryType: selection:listitem
      selection:key: dementia
      selection:label: Dementia
    /selection:listitem[9]:
      jcr:primaryType: selection:listitem
      selection:key: end-of-life-care
      selection:label: End of life care
    /selection:listitem[10]:
      jcr:primaryType: selection:listitem
      selection:key: genomics
      selection:label: Genomics
    /selection:listitem[11]:
      jcr:primaryType: selection:listitem
      selection:key: global-health
      selection:label: Global Health
    /selection:listitem[12]:
      jcr:primaryType: selection:listitem
      selection:key: health-inequalities
      selection:label: Health inequalities
    /selection:listitem[13]:
      jcr:primaryType: selection:listitem
      selection:key: infection-management
      selection:label: Infection management
    /selection:listitem[14]:
      jcr:primaryType: selection:listitem
      selection:key: learning-disability-and-autism
      selection:label: Learning disability and autism
    /selection:listitem[15]:
      jcr:primaryType: selection:listitem
      selection:key: long-term-conditions
      selection:label: Long-term conditions
    /selection:listitem[16]:
      jcr:primaryType: selection:listitem
      selection:key: maternity
      selection:label: Maternity
    /selection:listitem[17]:
      jcr:primaryType: selection:listitem
      selection:key: medicines-optimisation
      selection:label: Medicines Optimisation
    /selection:listitem[18]:
      jcr:primaryType: selection:listitem
      selection:key: mental-health
      selection:label: Mental Health
    /selection:listitem[19]:
      jcr:primaryType: selection:listitem
      selection:key: neonatal
      selection:label: Neonatal
    /selection:listitem[20]:
      jcr:primaryType: selection:listitem
      selection:key: nhs-screening--services
      selection:label: NHS screening  services
    /selection:listitem[21]:
      jcr:primaryType: selection:listitem
      selection:key: patient-safety
      selection:label: Patient safety
    /selection:listitem[22]:
      jcr:primaryType: selection:listitem
      selection:key: personalised-care
      selection:label: Personalised care
    /selection:listitem[23]:
      jcr:primaryType: selection:listitem
      selection:key: primary-care
      selection:label: Primary care
    /selection:listitem[24]:
      jcr:primaryType: selection:listitem
      selection:key: public-health-and-population-health
      selection:label: Public Health and population health
    /selection:listitem[25]:
      jcr:primaryType: selection:listitem
      selection:key: sexual-and-reproductive-health
      selection:label: Sexual and reproductive health
    /selection:listitem[26]:
      jcr:primaryType: selection:listitem
      selection:key: urgent-and-emergency-care
      selection:label: Urgent and Emergency Care
