/hippo:configuration/hippo:domains/content-{{ channelId }}-assets-and-gallery-readwrite:
  jcr:primaryType: hipposys:domain
  /assets-domain:
    jcr:primaryType: hipposys:domainrule
    /documents-only:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: true
      hipposys:facet: hippo:availability
      hipposys:type: String
      hipposys:value: live
    /non-publishable:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: nodetype
      hipposys:type: String
      hipposys:value: hippostd:publishable
    /{{ channelId }}-assets-and-descendants:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: true
      hipposys:facet: jcr:path
      hipposys:type: Reference
      hipposys:value: /content/assets/{{ channelId }}
  /rewrite:
    jcr:primaryType: hipposys:authrole
    hipposys:groups: [{{ channelId }}-author, {{ channelId }}-editor]
    hipposys:role: readwrite
    hipposys:users: []
  /gallery-domain:
    jcr:primaryType: hipposys:domainrule
    /documents-only:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: true
      hipposys:facet: hippo:availability
      hipposys:type: String
      hipposys:value: live
    /non-publishable:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: false
      hipposys:facet: nodetype
      hipposys:type: String
      hipposys:value: hippostd:publishable
    /{{ channelId }}-gallery-and-descendants:
      jcr:primaryType: hipposys:facetrule
      hipposys:equals: true
      hipposys:facet: jcr:path
      hipposys:type: Reference
      hipposys:value: /content/gallery/{{ channelId }}
