/hst:hst/hst:configurations/lks/hst:workspace/hst:pages/training-programme-page-training-programme-page:
  jcr:primaryType: hst:component
  hst:lastmodified: 2023-07-30T11:15:32.901+01:00
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponent
    hippo:identifier: cafebabe-cafe-babe-cafe-babecafebabe
    hst:label: Training Programme Page Main
    hst:lastmodified: 2023-07-30T11:15:57.103+01:00
    hst:xtype: hst.vbox
    /trainingprogramme-page:
      jcr:primaryType: hst:containeritemcomponent
      hst:componentclassname: uk.nhs.hee.web.components.TrainingProgrammePageComponent
      hst:iconpath: images/catalog-component-icons/simple-content.svg
      hst:label: Training Programme Page
      hst:parameternames: [document]
      hst:parametervalues: [training-programmes-pages/example-training-programme-page]
      hst:template: trainingprogrammepage-main
  /header:
    jcr:primaryType: hst:component
    /top:
      jcr:primaryType: hst:component
      /multi-org-logo:
        jcr:primaryType: hst:containercomponent
        hippo:identifier: f2a42c7a-42e2-45a0-bd69-a31516459acf
        hst:label: Multi org logo
        hst:lastmodified: 2023-07-30T11:15:57.103+01:00
        hst:xtype: hst.vbox
