/hst:hst/hst:configurations/lks/hst:workspace/hst:pages/training-program-collection-contentpage:
  jcr:primaryType: hst:component
  hst:lastmodified: 2023-09-20T16:42:36.396+01:00
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponent
    hippo:identifier: 43b034db-240d-480d-9a69-edea2f3c0cd4
    hst:label: Content Page Main
    hst:lastmodified: 2023-09-20T17:07:27.364+01:00
    hst:xtype: hst.vbox
    /trainingprogramme-colletion:
      jcr:primaryType: hst:containeritemcomponent
      hst:componentclassname: uk.nhs.hee.web.components.TrainingProgrammeCollectionComponent
      hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
      hst:label: Training Programme Collection Page
      hst:parameternames: [document]
      hst:parametervalues: [training-pages/training-programme-collection]
      hst:template: trainingprogrammecollection-main
  /header:
    jcr:primaryType: hst:component
    /top:
      jcr:primaryType: hst:component
      /multi-org-logo:
        jcr:primaryType: hst:containercomponent
        hippo:identifier: f2a42c7a-42e2-45a0-bd69-a31516459acf
        hst:label: Multi org logo
        hst:lastmodified: 2023-09-20T17:07:27.364+01:00
        hst:xtype: hst.vbox
