/hst:hst/hst:configurations/lks/hst:workspace/hst:sitemap/training-home:
  jcr:primaryType: hst:sitemapitem
  hst:componentconfigurationid: hst:pages/training-home-contentpage
  hst:lastmodified: 2023-05-19T13:24:33.184+01:00
  hst:pagetitle: training-home
