/hst:hst/hst:configurations/lks/hst:workspace/hst:sitemap/training-collection:
  jcr:primaryType: hst:sitemapitem
  hst:componentconfigurationid: hst:pages/training-collection-contentpage
  hst:lastmodified: 2023-11-10T12:04:04.012Z
  hst:pagetitle: Training collection
