/hst:hst/hst:configurations/lks/hst:workspace/hst:sitemap/training-programme-page:
  jcr:primaryType: hst:sitemapitem
  hst:componentconfigurationid: hst:pages/training-programme-page-training-programme-page
  hst:lastmodified: 2023-07-30T11:15:32.901+01:00
  hst:pagetitle: Training Programme Page
  /_default_:
    jcr:primaryType: hst:sitemapitem
    hst:componentconfigurationid: hst:pages/training-programme-page-training-programme-page
    hst:pagetitle: Training Programme Page
