/hst:hst/hst:configurations/lks/hst:workspace/hst:sitemap/training-program-page:
  jcr:primaryType: hst:sitemapitem
  hst:componentconfigurationid: hst:pages/training-program-page-contentpage
  hst:lastmodified: 2023-05-31T11:20:21.029+01:00
  hst:pagetitle: Training Program Page
