/content/documents/website-testing/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 3cb55cd8-1c39-4352-b086-9893d7fa974e
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: 2c9b5fd8-1286-4738-b02f-4e56825cef02
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 17d652e5-9061-4ab1-b24f-5e692e520524
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 413aee68-e64f-4f8e-a86e-c91b4e6e587b
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 82820827-a2d6-42f8-beed-d1e45769683b
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 48ebc96a-3f1e-47d7-9ccc-59b9e20a387a
    hippotranslation:locale: en
