/content/documents/health-careers/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: fd0dafab-79b5-43a4-9dbf-d50875e5c1c9
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: fb2bf26d-7f2e-45e3-a99d-5c603e25e9aa
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 0d663cf4-d791-4c58-9530-f976cca12985
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 951da5cb-b656-4a8f-a8a4-82d90c3dae23
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 5b59056c-2b2d-4981-ac66-b38d1f6052b2
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: d9daaeac-17c0-41ec-8948-109ee3a43e4a
    hippotranslation:locale: en
