/hst:hst/hst:configurations/lks/hst:workspace/hst:pages/training-program-page-contentpage:
  jcr:primaryType: hst:component
  hst:lastmodified: 2023-05-31T11:20:21.029+01:00
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponent
    hippo:identifier: 43b034db-240d-480d-9a69-edea2f3c0cd4
    hst:label: Content Page Main
    hst:lastmodified: 2023-05-31T11:26:07.119+01:00
    hst:xtype: hst.vbox
    /trainingprogramme-page:
      jcr:primaryType: hst:containeritemcomponent
      hst:componentclassname: uk.nhs.hee.web.components.TrainingProgrammePageComponent
      hst:iconpath: images/catalog-component-icons/simple-content.svg
      hst:label: Training Programme Page
      hst:parameternames: [document]
      hst:parametervalues: [training-programmes-pages/training-programmes-page]
      hst:template: trainingprogrammepage-main
  /header:
    jcr:primaryType: hst:component
    /top:
      jcr:primaryType: hst:component
      /multi-org-logo:
        jcr:primaryType: hst:containercomponent
        hippo:identifier: f2a42c7a-42e2-45a0-bd69-a31516459acf
        hst:label: Multi org logo
        hst:lastmodified: 2023-05-31T11:26:07.119+01:00
        hst:xtype: hst.vbox
