/hst:hst/hst:configurations/lks/hst:workspace/hst:pages/training-collection-contentpage:
  jcr:primaryType: hst:component
  hst:lastmodified: 2023-11-10T12:04:04.012Z
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponent
    hippo:identifier: 43b034db-240d-480d-9a69-edea2f3c0cd4
    hst:label: Content Page Main
    hst:lastmodified: 2023-11-16T08:36:14.598Z
    hst:xtype: hst.vbox
    /training-listing:
      jcr:primaryType: hst:containeritemcomponent
      hst:componentclassname: uk.nhs.hee.web.components.TrainingListingPageComponent
      hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
      hst:label: Training collection page
      hst:parameternames: [document]
      hst:parametervalues: [listing-pages/training]
      hst:template: taxonomybasedlisting-main
  /header:
    jcr:primaryType: hst:component
    /top:
      jcr:primaryType: hst:component
      /multi-org-logo:
        jcr:primaryType: hst:containercomponent
        hippo:identifier: f2a42c7a-42e2-45a0-bd69-a31516459acf
        hst:label: Multi org logo
        hst:lastmodified: 2023-11-10T12:04:36.499Z
        hst:xtype: hst.vbox
        /multi-org-logo:
          jcr:primaryType: hst:containeritemcomponent
          hst:componentclassname: uk.nhs.hee.web.components.MultiOrgLogoComponent
          hst:iconpath: _cmsinternal/images/catalog-component-icons/carousel.svg
          hst:label: Multi org logo
          hst:parameternames: [document]
          hst:parametervalues: [listing-pages/training]
          hst:template: multi-org-logo
