definitions:
  config:
    /hippo:namespaces/hee/trainingProgrammePage:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: fd777d91-29b3-41bb-8a6f-f25e0ddea41d
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 5c11a6f7-361b-4951-8d3a-f642ac60b767
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 07e45714-8e91-4f49-a40e-4f463ce1d439
          hipposysedit:node: true
          hipposysedit:supertype: ['hee:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.heecmsplatform.com/hee/nt/1.0
          hipposysedit:validators: ['hee:mandatory-training-journey-validator']
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required]
          /logoGroup:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:logoGroup
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /heroImage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:microHero
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [required]
          /regions:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:regions
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /cardImage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:cardImage
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [required]
          /overview:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:overview
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, required]
          /rightHandBlocks:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:rightHandBlocks
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /trainingJourneyPrerequisites:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:trainingJourneyPrerequisites
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /trainingJourneyOptions:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:trainingJourneyOptions
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /trainingJourneySummary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:trainingJourneySummary
            hipposysedit:primary: false
            hipposysedit:type: String
          /applicationButtonTitle:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:applicationButtonTitle
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /applicationButtonLink:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:applicationButtonLink
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required, url]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: hee:trainingProgrammePage
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 326662b5-1cfd-406d-b69d-a34fc1ff6294
          hee:summary: ''
          hee:title: ''
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2023-05-17T14:09:18.030+01:00
          hippostdpubwf:lastModificationDate: 2023-05-17T14:09:18.030+01:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: ''
          hippotranslation:locale: ''
          hee:trainingJourneySummary: ''
          hee:applicationButtonTitle: ''
          hee:applicationButtonLink: ''
          /hee:microHero:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /hee:logoGroup:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /hee:cardImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            extension.right: ${cluster.id}.right
            wicket.extensions: [extension.left, extension.right]
            extension.left: ${cluster.id}.left
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            hint: Enter a title e.g. Dental Core Training (60 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Summary
            field: summary
            hint: Provide a summary of the training programme ( 300 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '300'
          /microHero:
            jcr:primaryType: frontend:plugin
            caption: Micro-hero image
            field: heroImage
            hint: Add an image that's 260 pixels high and 1600 pixels wide.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /logoGroup:
            jcr:primaryType: frontend:plugin
            caption: Logo group
            field: logoGroup
            hint: Browse for the logos to override the default header
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:logoGroup']
          /cardImage:
            jcr:primaryType: frontend:plugin
            caption: Card image
            field: cardImage
            hint: Add an image that's 200 pixels high and 310 pixels wide
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /overview:
            jcr:primaryType: frontend:plugin
            caption: Overview
            compoundList: hee:appliesToBoxReference,hippostd:html,hippogallerypicker:imagelink,hee:insetReference,hee:mediaEmbedReference,hee:richTextReference,hee:statementCardReference,hee:warningCalloutReference
            contentPickerType: links
            field: overview
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /applicationButtonTitle:
            jcr:primaryType: frontend:plugin
            caption: Application button title
            field: applicationButtonTitle
            hint: Enter a button title e.g. Apply in Oriel  (60 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /applicationButtonLink:
            jcr:primaryType: frontend:plugin
            caption: Application button link
            field: applicationButtonLink
            hint: Please enter a URL to an application system such as Oriel
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /rightHandBlocks:
            jcr:primaryType: frontend:plugin
            caption: Right hand objects
            compoundList: hee:contactCardWithDescriptionReference,hee:externalLinksCardReference,hee:fileLinksCardReference,hee:internalLinksCardReference,hee:QuickLinks
            contentPickerType: links
            field: rightHandBlocks
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.right.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /trainingJourneySummary:
            jcr:primaryType: frontend:plugin
            caption: Training journey summary
            field: trainingJourneySummary
            hint: Enter a summary for the training journey (120 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '120'
          /trainingJourneyPrerequisites:
            jcr:primaryType: frontend:plugin
            caption: Training journey prerequisites
            field: trainingJourneyPrerequisites
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            hint: Please browse to and select at least one Training programme page
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              last.visited.nodetypes: []
              nodetypes: ['hee:trainingProgrammePage']
          /trainingJourneyOptions:
            jcr:primaryType: frontend:plugin
            caption: Training journey optional routes
            field: trainingJourneyOptions
            hint: Please browse to and select at least one Training programme page
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:trainingProgrammePage']
          /regions:
            jcr:primaryType: frontend:plugin
            caption: Regions
            compoundList: hee:navMap
            contentPickerType: links
            field: regions
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig