definitions:
  config:
    /hippo:namespaces/hee/trainingProgrammeCollection:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: a96c51c9-a6f7-44ab-b312-c945e9be54bb
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 56211a4b-9146-4af8-9a78-c9a0294aec62
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 8fae6ada-220c-4277-88c1-b2e9323c5a46
          hipposysedit:node: true
          hipposysedit:supertype: ['hee:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.heecmsplatform.com/hee/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
          /microHero:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:microHero
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /logoGroup:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:logoGroup
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /pageSize:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:pageSize
            hipposysedit:primary: false
            hipposysedit:type: Long
            hipposysedit:validators: [required]
          /addToAZ:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:addToAZ
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /subtitle:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:subtitle
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: hee:trainingProgrammeCollection
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: f751e6ec-1f9d-4623-8f73-73870e332ab9
          hee:addToAZ: false
          hee:pageSize: 10
          hee:subtitle: ''
          hee:summary: ''
          hee:title: ''
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2022-12-02T14:26:11.069Z
          hippostdpubwf:lastModificationDate: 2022-12-02T14:26:11.069Z
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /hee:microHero:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /hee:logoGroup:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Page title
            field: title
            hint: Enter the page title (60 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /subtitle:
            jcr:primaryType: frontend:plugin
            caption: Page subtitle
            field: subtitle
            hint: Enter the page subtitle (60 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Summary
            field: summary
            hint: Summarise this page (300 character limit)
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '300'
          /microHero:
            jcr:primaryType: frontend:plugin
            caption: Micro-hero image
            field: microHero
            hint: Add an image that’s 260 pixels high and 1600 pixels wide
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /logoGroup:
            jcr:primaryType: frontend:plugin
            caption: Logo group
            field: logoGroup
            hint: Please browse to a logo asset that you would like to override the
              default header logo
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:logoGroup']
          /pageSize:
            jcr:primaryType: frontend:plugin
            caption: Page size
            field: pageSize
            hint: Enter the number of results to display per page
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /addToAZ:
            jcr:primaryType: frontend:plugin
            caption: Add to A to Z
            field: addToAZ
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
