definitions:
  config:
    /hippo:namespaces/hee/trainingProgrammesHomepage:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 68acf998-de2a-45b2-863e-5f6bd7b20f19
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 3981ed6a-0f58-48fd-8a73-5a008e5d72ef
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: a1416b6e-c1fd-4103-bef7-6d7ce3ba0eed
          hipposysedit:node: true
          hipposysedit:supertype: ['hee:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.heecmsplatform.com/hee/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /subtitle:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:subtitle
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /logoGroup:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:logoGroup
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
            hipposysedit:validators: [optional]
          /addToAZ:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:addToAZ
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /heroImage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:heroImage
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [required]
          /programmeDescription:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:programmeDescription
            hipposysedit:primary: false
            hipposysedit:type: Text
          /overview:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:overview
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            hipposysedit:validators: [required]
          /rightHandBlocks:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:rightHandBlocks
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /pathways:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:pathways
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, 'hee:image-link-content-block-validator', 'hee:html-content-block-validator']
          /trainingRoutes:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:trainingRoutes
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, required, 'hee:html-content-block-validator']
          /support:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:support
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, 'hee:html-content-block-validator']
          /regions:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:regions
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /featuredContentBlock:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:featuredContentBlock
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: hee:trainingProgrammesHomepage
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 44de6668-3b9d-4919-9f2e-0d4263e7b345
          hee:addToAZ: false
          hee:subtitle: ''
          hee:title: ''
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2021-02-05T11:01:21.185+07:00
          hippostdpubwf:lastModificationDate: 2021-02-05T11:01:21.184+07:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          hee:programmeDescription: ''
          /hee:logoGroup:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /hee:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /hee:overview:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /hee:featuredContentBlock:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            extension.right: ${cluster.id}.right
            wicket.extensions: [extension.left, extension.right]
            extension.left: ${cluster.id}.left
          /title:
            jcr:primaryType: frontend:plugin
            caption: Page title
            field: title
            hint: Page title must be 60 characters or fewer.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /subtitle:
            jcr:primaryType: frontend:plugin
            caption: Page subtitle
            field: subtitle
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '120'
          /heroImage:
            jcr:primaryType: frontend:plugin
            caption: Hero image
            field: heroImage
            hint: Add an image that's 380 pixels high and 1600 pixels wide.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /logoGroup:
            jcr:primaryType: frontend:plugin
            caption: Logo group
            field: logoGroup
            hint: Browse for the logos to override the default header
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:logoGroup']
          /programmeDescription:
            jcr:primaryType: frontend:plugin
            caption: Programme description
            field: programmeDescription
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /overview:
            jcr:primaryType: frontend:plugin
            caption: Overview
            field: overview
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              ckeditor.config.appended.json: '{ removeButtons: "PickImage,Table,Source",
                stylesSet: "styles_without_h1-h2:./styles_without_h1-h2.js" }'
          /pathways:
            jcr:primaryType: frontend:plugin
            caption: Pathways
            compoundList: hee:ActionLink,hee:detailsReference,hee:htmlWithoutHeadingOneAndTwo,hee:imageBlock,hee:insetReference,hee:quoteReference,hee:richTextReference
            contentPickerType: links
            field: pathways
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /trainingRoutes:
            jcr:primaryType: frontend:plugin
            caption: Training Routes
            compoundList: hee:ActionLink,hee:blockLinksReference,hee:htmlWithoutHeadingOneAndTwo,hee:richTextReference
            contentPickerType: links
            field: trainingRoutes
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /support:
            jcr:primaryType: frontend:plugin
            caption: Support
            compoundList: hee:detailsReference,hee:expanderGroupReference,hee:htmlWithoutHeadingOneAndTwo,hee:googleMapReference,hee:insetReference,hee:richTextReference
            contentPickerType: links
            field: support
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /regions:
            jcr:primaryType: frontend:plugin
            caption: Regions
            compoundList: hee:navMap
            contentPickerType: links
            field: regions
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /addToAZ:
            jcr:primaryType: frontend:plugin
            caption: Add to A to Z
            field: addToAZ
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /rightHandBlocks:
            jcr:primaryType: frontend:plugin
            caption: Right hand objects
            compoundList: hee:contactCardWithDescriptionReference,hee:ctaCardReference,hee:externalLinksCardReference,hee:internalLinksCardReference,hee:QuickLinks
            contentPickerType: links
            field: rightHandBlocks
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              showCompoundNames: 'true'
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /featuredContentBlock:
            jcr:primaryType: frontend:plugin
            caption: Featured content
            field: featuredContentBlock
            hint: Select the featured content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:featuredContent']
