definitions:
  config:
    /hippo:namespaces/hee/trainingProgrammesHomepage:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 68acf998-de2a-45b2-863e-5f6bd7b20f19
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 3981ed6a-0f58-48fd-8a73-5a008e5d72ef
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 97f26182-a8ee-4699-a1c8-4962c2e2dacb
          hipposysedit:node: true
          hipposysedit:supertype: ['hee:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.heecmsplatform.com/hee/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required]
          /logoGroup:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:logoGroup
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
            hipposysedit:validators: [optional]
          /boolean:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:addToAZ
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /heroImage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:heroImage
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /text:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:text
            hipposysedit:primary: false
            hipposysedit:type: Text
          /overview:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:overview
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            hipposysedit:validators: [required]
          /rightHandBlocks:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:rightHandBlocks
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /pathways:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:pathways
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /trainingRoutes:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:trainingRoutes
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, required]
          /support:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:support
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /regions:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:regions
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
        /hipposysedit:nodetype[2]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: a3872dd8-4d4e-41f6-a170-fa10065d7de7
          hipposysedit:node: true
          hipposysedit:supertype: ['hee:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /summary:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:summary
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required]
          /logoGroup:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:logoGroup
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
            hipposysedit:validators: [optional]
          /boolean:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:addToAZ
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /heroImage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:heroImage
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /text:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:text
            hipposysedit:primary: false
            hipposysedit:type: Text
          /overview:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hee:overview
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            hipposysedit:validators: [required]
          /rightHandBlocks:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:rightHandBlocks
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /pathways:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:pathways
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /trainingRoutes:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:trainingRoutes
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator, required]
          /support:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:support
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /regions:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: hee:regions
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: hee:trainingProgrammesHomepage
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: a58fc7d6-0ffb-4f39-a556-92e279b8be67
          hee:addToAZ: false
          hee:summary: ''
          hee:title: ''
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2021-02-05T11:01:21.185+07:00
          hippostdpubwf:lastModificationDate: 2021-02-05T11:01:21.184+07:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          hee:text: ''
          /hee:logoGroup:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /hee:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /hee:overview:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
        /hipposysedit:prototype[2]:
          jcr:primaryType: nt:unstructured
          jcr:mixinTypes: ['hippostd:publishableSummary', 'hippostd:relaxed', 'hippostdpubwf:document',
            'hippotranslation:translated', 'mix:referenceable']
          jcr:uuid: a0c3281d-de99-42ee-9710-26d2c993b11a
          hee:addToAZ: false
          hee:summary: ''
          hee:text: ''
          hee:title: ''
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2021-02-05T11:01:21.185+07:00
          hippostdpubwf:lastModificationDate: 2021-02-05T11:01:21.184+07:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /hee:logoGroup:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /hee:heroImage:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /hee:overview:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Page title
            field: title
            hint: Page title must be 60 characters or fewer.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxlength: '60'
          /summary:
            jcr:primaryType: frontend:plugin
            caption: Summary
            field: summary
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /heroImage:
            jcr:primaryType: frontend:plugin
            caption: Hero image
            field: heroImage
            hint: Add an image that's 380 pixels high and 1600 pixels wide.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /logoGroup:
            jcr:primaryType: frontend:plugin
            caption: Logo group
            field: logoGroup
            hint: Browse for the logos to override the default header
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hee:logoGroup']
          /text:
            jcr:primaryType: frontend:plugin
            caption: Caption
            field: text
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /overview:
            jcr:primaryType: frontend:plugin
            caption: Overview
            field: overview
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              ckeditor.config.appended.json: '{ removeButtons: "PickImage,Table,Source"
                }'
          /pathways:
            jcr:primaryType: frontend:plugin
            caption: Pathways
            compoundList: hippostd:html,hippogallerypicker:imagelink,hee:richTextReference
            contentPickerType: links
            field: pathways
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /trainingRoutes:
            jcr:primaryType: frontend:plugin
            caption: Training Routes
            compoundList: hee:ActionLink,hee:blockLinksReference,hippostd:html,hee:richTextReference
            contentPickerType: links
            field: trainingRoutes
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /support:
            jcr:primaryType: frontend:plugin
            caption: Support
            compoundList: hee:ActionLink,hippostd:html,hee:richTextReference
            contentPickerType: links
            field: support
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /regions:
            jcr:primaryType: frontend:plugin
            caption: Regions
            compoundList: hee:navMap
            contentPickerType: links
            field: regions
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /addToAZ:
            jcr:primaryType: frontend:plugin
            caption: Add to A to Z
            field: boolean
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /rightHandBlocks:
            jcr:primaryType: frontend:plugin
            caption: Right hand objects
            compoundList: hee:contactCardWithDescriptionReference,hee:ctaCardReference,hee:externalLinksCardReference,hee:internalLinksCardReference,hee:QuickLinks
            contentPickerType: links
            field: rightHandBlocks
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
