/content/documents/lks/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 304d7c99-36c0-498e-98e7-1b5f20c5bdf1
  hippo:name: Settings
  hippostd:foldertype: [new-folder]
  hippotranslation:id: e79b221d-68ea-4866-9186-0cb46c67baf9
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: 3f76d453-f553-4b6d-9295-cfb9d58216ff
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    /phase-banner:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 39f0efa1-90bf-4676-ae89-92e8143fde25
      hippo:name: Phase banner
      hippo:versionHistory: fcbe0650-6f3f-4957-ac2b-0cce6e120823
      /phase-banner[1]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 050c3738-3f14-4916-94d6-7507ab1e4065
        hee:phase: beta
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T23:19:27.646Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: aaac4d44-0b93-4adc-8497-a7a799e4e452
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <p>&nbsp;This is a new website&nbsp;– your&nbsp;feedback&nbsp;will help us to improve it.</p>

            <p>Sed porttitor lectus nibh.??</p>

            <p>Test</p>
      /phase-banner[2]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
        jcr:uuid: 824dd61c-7365-4d40-96f7-1bf41a34368d
        hee:phase: beta
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T23:30:51.211Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: aaac4d44-0b93-4adc-8497-a7a799e4e452
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <p>&nbsp;This is a new website&nbsp;– your&nbsp;feedback&nbsp;will help us to improve it.</p>

            <p>Sed porttitor lectus nibh.??</p>

            <p>Test</p>
      /phase-banner[3]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 6d0551b2-95c2-4356-aa61-4db80c925fd3
        hee:phase: beta
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T16:32:10.097Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2023-01-13T17:05:24.463Z
        hippotranslation:id: aaac4d44-0b93-4adc-8497-a7a799e4e452
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <p>&nbsp;This is a new website&nbsp;– your&nbsp;feedback&nbsp;will help us to improve it.</p>

            <p>Sed porttitor lectus nibh.??</p>
    /announcement-banner:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 30be7c6e-ad72-4fb2-a0dd-81b5b5a702bf
      hippo:name: Announcement banner
      hippo:versionHistory: c85443cd-5265-459f-8aaf-18bf178971db
      /announcement-banner[1]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: e90b7e13-e23a-4b2c-9925-b0c3db71e63c
        hee:phase: ''
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T13:13:49.959Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: cfca07e6-19f1-4f8a-9029-bd60c69aa09f
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Announcement.&nbsp;Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="home">this is the link</a></p>
          /home:
            jcr:primaryType: hippo:facetselect
            hippo:docbase: ef78c935-2f90-48d2-919f-5f99073f1832
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /announcement-banner[2]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 7177b67c-3791-4979-b31a-1dd5d48fc51a
        hee:phase: ''
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T16:26:39.841Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: cfca07e6-19f1-4f8a-9029-bd60c69aa09f
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Announcement.&nbsp;Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="home">this is the link</a></p>
          /home:
            jcr:primaryType: hippo:facetselect
            hippo:docbase: ef78c935-2f90-48d2-919f-5f99073f1832
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /announcement-banner[3]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 04a1f154-d381-43c7-9675-c2bb65c65033
        hee:phase: ''
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T13:13:49.959Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2023-01-13T13:13:52.645Z
        hippotranslation:id: cfca07e6-19f1-4f8a-9029-bd60c69aa09f
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Announcement.&nbsp;Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="home">this is the link</a></p>
          /home:
            jcr:primaryType: hippo:facetselect
            hippo:docbase: ef78c935-2f90-48d2-919f-5f99073f1832
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
    /alert-banner:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 854422f6-0340-492b-8567-bb4607857aaf
      hippo:name: Alert banner
      hippo:versionHistory: d027beb2-7155-4c0d-88b4-242b2f5c079a
      /alert-banner[1]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: a07898c3-717b-40c2-b60a-f888d3c211fb
        hee:phase: ''
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T11:58:00.297Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 3b335ea4-ef8d-4472-b026-af98c911ee34
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Alert.&nbsp;Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
      /alert-banner[2]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 574f9a7a-17fb-4243-93eb-5675dcade4ae
        hee:phase: ''
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostd:transferable: false
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T12:02:29.158Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 3b335ea4-ef8d-4472-b026-af98c911ee34
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Alert.&nbsp;Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
      /alert-banner[3]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 35b34baf-1b5b-45ae-b049-ec4071c95ed6
        hee:phase: ''
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T11:58:00.297Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2023-01-13T11:58:02.960Z
        hippotranslation:id: 3b335ea4-ef8d-4472-b026-af98c911ee34
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is an Alert.&nbsp;Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
    /mourning-banner:
      jcr:primaryType: hippo:handle
      jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
      jcr:uuid: 28041598-5696-4534-8ea5-e5aabc7a4016
      hippo:name: Mourning banner
      hippo:versionHistory: 840e29dc-d9c8-4703-b068-ca5f9eb1866f
      /mourning-banner[1]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:versionable']
        jcr:uuid: 63eb5b15-0a9a-41bf-967f-f7d932e737a3
        hee:phase: ''
        hippo:availability: [preview]
        hippostd:retainable: false
        hippostd:state: unpublished
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T13:14:03.259Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 038efe49-0431-4575-91c5-ff5939bca2ab
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is a Mourning.&nbsp;Nulla quis lorem ut libero malesuada feugiat.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="http://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
      /mourning-banner[2]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 0578922b-8ead-4e21-b9e4-e84109c3d236
        hee:phase: ''
        hippo:availability: []
        hippostd:retainable: false
        hippostd:state: draft
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T13:13:54.467Z
        hippostdpubwf:lastModifiedBy: admin
        hippotranslation:id: 038efe49-0431-4575-91c5-ff5939bca2ab
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is a Mourning.&nbsp;Nulla quis lorem ut libero malesuada feugiat.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="http://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
      /mourning-banner[3]:
        jcr:primaryType: hee:banner
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 5cfb88e1-d130-4bc3-a5dc-6f67f753f4cb
        hee:phase: ''
        hippo:availability: [live]
        hippostd:retainable: false
        hippostd:state: published
        hippostdpubwf:createdBy: admin
        hippostdpubwf:creationDate: 2023-01-10T15:38:07.541Z
        hippostdpubwf:lastModificationDate: 2023-01-13T13:14:03.259Z
        hippostdpubwf:lastModifiedBy: admin
        hippostdpubwf:publicationDate: 2023-01-13T17:05:24.542Z
        hippotranslation:id: 038efe49-0431-4575-91c5-ff5939bca2ab
        hippotranslation:locale: en
        /hee:bannerContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>H2 - This is a Mourning.&nbsp;Nulla quis lorem ut libero malesuada feugiat.</h2>

            <h3>H3 - This is the alert text and&nbsp;<a href="http://www.hee.nhs.uk/">this is the link</a></h3>

            <p>Body&nbsp;- This is banner body copy&nbsp;<a href="https://www.hee.nhs.uk/">this is the link</a></p>
