/content/documents/lks/training-programmes-pages:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c5992e29-6f86-4a1f-87d6-7a1eca87fa4e
  hippo:name: Training Programmes Pages
  hippostd:foldertype: [new-trainingProgrammePage-folder, new-trainingProgrammePage-document]
  hippotranslation:id: ce2452ee-f974-429a-8e3a-8413868fae36
  hippotranslation:locale: en
  /training-programmes-page:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 100d42bc-8c13-4c27-aa90-676525d65ec4
    hippo:name: Training Programmes Page
    hippo:versionHistory: 6ea22782-3f10-412c-9882-25ee6428f35b
    /training-programmes-page[1]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: c10adc7a-4906-4441-970c-dbd7be3e69cf
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 0001-01-01T12:00:00Z
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:opening: 0001-01-01T12:00:00Z
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hee:trainingType: core
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostd:transferable: false
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T11:13:26.203+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
    /training-programmes-page[2]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: a6783064-188f-499f-849f-e4a7ad959885
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 0001-01-01T12:00:00Z
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:opening: 0001-01-01T12:00:00Z
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hee:trainingType: core
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T11:13:25.927+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
    /training-programmes-page[3]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: b48a7187-875c-4ea3-9b9c-fe171c9ac688
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 0001-01-01T12:00:00Z
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:opening: 0001-01-01T12:00:00Z
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hee:trainingType: core
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T11:13:25.927+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2023-08-23T11:13:31.099+01:00
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
