/content/documents/lks/training-programmes-pages:
  .meta:order-before: listing-pages
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c5992e29-6f86-4a1f-87d6-7a1eca87fa4e
  hippo:name: Training Programmes Pages
  hippostd:foldertype: [new-training-programmepage-folder, new-training-programmepage-document]
  hippotranslation:id: ce2452ee-f974-429a-8e3a-8413868fae36
  hippotranslation:locale: en
  /example-training-programme-page:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 6bf10fab-1586-4d3f-9d3a-441abd44fb15
    hippo:name: Example training programme page
    hippo:versionHistory: f83a1aae-3f99-45e7-8d82-00fc508a0af3
    /example-training-programme-page[1]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 4b62a045-f40e-47f1-ae2f-50f4e8496736
      hee:closing: 2023-09-30T15:41:00+01:00
      hee:competitionRatio: 93.0
      hee:discipline: general-practice
      hee:duration: 12
      hee:fillRate: 12
      hee:opening: 2023-06-14T15:41:00+01:00
      hee:professions: [advanced-critical-care-practitioner-anaesthesia-associate]
      hee:recruitmentFormat: standard
      hee:summary: A summary of the training programme that we have compiled for you.
        A lot of information in a small amount of space but all very useful
      hee:title: Example training programme page title
      hee:topics: []
      hee:trainingType: core
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-06-12T17:52:12.862+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T22:32:53.836+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: b95772fc-4f22-4459-a278-3f5b9fd49b2f
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: d2e99831-2b29-4868-bb07-2445a3c68732
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: ed90374f-89d9-47d5-bbc8-156175833866
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:applicationInformation:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:overview:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Overview text is added here and wil lapper on the front page as part of that page</p>

          <p>&nbsp;</p>

          <p>When you switch to a new page, the overview text will not show</p>
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 84a8a4db-d4bc-43c7-86b9-c4dd0dd26f33
    /example-training-programme-page[2]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 6f3deaef-0dde-457e-b0b1-e2d0659abb3c
      hee:closing: 2023-09-30T15:41:00+01:00
      hee:competitionRatio: 93.0
      hee:discipline: general-practice
      hee:duration: 12
      hee:fillRate: 12
      hee:opening: 2023-06-14T15:41:00+01:00
      hee:professions: [advanced-critical-care-practitioner-anaesthesia-associate]
      hee:recruitmentFormat: standard
      hee:summary: A summary of the training programme that we have compiled for you.
        A lot of information in a small amount of space but all very useful
      hee:title: Example training programme page title
      hee:topics: []
      hee:trainingType: core
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-06-12T17:52:12.862+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T22:54:39.442+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: b95772fc-4f22-4459-a278-3f5b9fd49b2f
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: d2e99831-2b29-4868-bb07-2445a3c68732
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: ed90374f-89d9-47d5-bbc8-156175833866
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:applicationInformation:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:overview:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Overview text is added here and wil lapper on the front page as part of that page</p>

          <p>&nbsp;</p>

          <p>When you switch to a new page, the overview text will not show</p>
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 84a8a4db-d4bc-43c7-86b9-c4dd0dd26f33
    /example-training-programme-page[3]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 9cdf3b98-acf1-4826-a24b-0b6c6ec26329
      hee:closing: 2023-09-30T15:41:00+01:00
      hee:competitionRatio: 93.0
      hee:discipline: general-practice
      hee:duration: 12
      hee:fillRate: 12
      hee:opening: 2023-06-14T15:41:00+01:00
      hee:professions: [advanced-critical-care-practitioner-anaesthesia-associate]
      hee:recruitmentFormat: standard
      hee:summary: A summary of the training programme that we have compiled for you.
        A lot of information in a small amount of space but all very useful
      hee:title: Example training programme page title
      hee:topics: []
      hee:trainingType: core
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-06-12T17:52:12.862+01:00
      hippostdpubwf:lastModificationDate: 2023-08-23T22:54:39.442+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2023-08-23T22:54:45.735+01:00
      hippotranslation:id: b95772fc-4f22-4459-a278-3f5b9fd49b2f
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: d2e99831-2b29-4868-bb07-2445a3c68732
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: ed90374f-89d9-47d5-bbc8-156175833866
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:applicationInformation:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:overview:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>Overview text is added here and wil lapper on the front page as part of that page</p>

          <p>&nbsp;</p>

          <p>When you switch to a new page, the overview text will not show</p>
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 84a8a4db-d4bc-43c7-86b9-c4dd0dd26f33
