/content/documents/lks/training-programmes-pages:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: c5992e29-6f86-4a1f-87d6-7a1eca87fa4e
  hippo:name: Training Programmes Pages
  hippostd:foldertype: [new-trainingProgrammePage-folder, new-trainingProgrammePage-document]
  hippotranslation:id: ce2452ee-f974-429a-8e3a-8413868fae36
  hippotranslation:locale: en
  /training-programmes-page:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 100d42bc-8c13-4c27-aa90-676525d65ec4
    hippo:name: Training Programmes Page
    hippo:versionHistory: b7840ca6-5036-4316-81a6-c3198cd37388
    /training-programmes-page[1]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: c10adc7a-4906-4441-970c-dbd7be3e69cf
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 2025-09-01T13:29:00+05:30
      hee:competitionRatio: 2.56
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:fillRate: 75
      hee:globalRecruitmentFormat: [standard]
      hee:globalRecruitmentFormat__with_ancestors: [standard]
      hee:globalTaxonomyHealthcareTopics: []
      hee:globalTaxonomyHealthcareTopics__with_ancestors: []
      hee:globalTaxonomyProfessions: [dental_professionals, clinical_manager, nurses,
        district_nurse]
      hee:globalTaxonomyProfessions__with_ancestors: [dental_professionals, management_professionals,
        clinical_manager, nurses, district_nurse]
      hee:globalTaxonomyTrainingType: [formal_training]
      hee:globalTaxonomyTrainingType__with_ancestors: [formal_training]
      hee:opening: 2023-09-01T13:29:00+05:30
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-31T14:22:53.028+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview[1]:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
      /hee:applicationInformation[1]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:applicationInformation[2]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:applicationInformation[3]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: f4fb5b81-8054-495f-b1bd-7cf0f0aba641
      /hee:applicationInformation[4]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 9071bfc1-35e4-4cb8-852c-c91f97fb43f0
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 91a74faa-0fb9-4a0c-ac70-ed3becedd670
      /hee:overview[2]:
        jcr:primaryType: hee:detailsReference
        /hee:detailsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: fdf33d93-cb1f-4a12-a954-c5f187e767d2
      /hee:overview[3]:
        jcr:primaryType: hee:expanderGroupReference
        /hee:expanderContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: c6a5f1d2-0b3e-4f0f-bc1a-375146b710fd
      /hee:overview[4]:
        jcr:primaryType: hee:googleMapReference
        /hee:googleMapContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9f09cb7d-5099-4dba-8683-fc453dfdcb16
      /hee:overview[5]:
        jcr:primaryType: hee:tableReference
        /hee:tabledataContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 94afb585-a7a3-4eb9-a2fd-0836aec4d05a
      /hee:overview[6]:
        jcr:primaryType: hee:expanderTableReference
        /hee:expanderTableContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 4c72c1f9-22a7-4819-be39-f1cf1c54e21a
      /hee:overview[7]:
        jcr:primaryType: hee:tabsReference
        /hee:tabsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9dfce526-0f2e-4b45-a6cd-c0ce59d229bf
    /training-programmes-page[2]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: a6783064-188f-499f-849f-e4a7ad959885
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 2025-09-01T13:29:00+05:30
      hee:competitionRatio: 2.56
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:fillRate: 75
      hee:globalRecruitmentFormat: [standard]
      hee:globalRecruitmentFormat__with_ancestors: [standard]
      hee:globalTaxonomyHealthcareTopics: []
      hee:globalTaxonomyHealthcareTopics__with_ancestors: []
      hee:globalTaxonomyProfessions: [dental_professionals, clinical_manager, nurses,
        district_nurse]
      hee:globalTaxonomyProfessions__with_ancestors: [dental_professionals, management_professionals,
        clinical_manager, nurses, district_nurse]
      hee:globalTaxonomyTrainingType: [formal_training]
      hee:globalTaxonomyTrainingType__with_ancestors: [formal_training]
      hee:opening: 2023-09-01T13:29:00+05:30
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-31T14:22:52.951+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview[1]:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
      /hee:applicationInformation[1]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:applicationInformation[2]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:applicationInformation[3]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: f4fb5b81-8054-495f-b1bd-7cf0f0aba641
      /hee:applicationInformation[4]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 9071bfc1-35e4-4cb8-852c-c91f97fb43f0
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 91a74faa-0fb9-4a0c-ac70-ed3becedd670
      /hee:overview[2]:
        jcr:primaryType: hee:detailsReference
        /hee:detailsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: fdf33d93-cb1f-4a12-a954-c5f187e767d2
      /hee:overview[3]:
        jcr:primaryType: hee:expanderGroupReference
        /hee:expanderContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: c6a5f1d2-0b3e-4f0f-bc1a-375146b710fd
      /hee:overview[4]:
        jcr:primaryType: hee:googleMapReference
        /hee:googleMapContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9f09cb7d-5099-4dba-8683-fc453dfdcb16
      /hee:overview[5]:
        jcr:primaryType: hee:tableReference
        /hee:tabledataContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 94afb585-a7a3-4eb9-a2fd-0836aec4d05a
      /hee:overview[6]:
        jcr:primaryType: hee:expanderTableReference
        /hee:expanderTableContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 4c72c1f9-22a7-4819-be39-f1cf1c54e21a
      /hee:overview[7]:
        jcr:primaryType: hee:tabsReference
        /hee:tabsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9dfce526-0f2e-4b45-a6cd-c0ce59d229bf
    /training-programmes-page[3]:
      jcr:primaryType: hee:trainingProgrammePage
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: b48a7187-875c-4ea3-9b9c-fe171c9ac688
      hee:applicationButtonLink: http://www.google.com
      hee:applicationButtonTitle: Application button
      hee:closing: 2025-09-01T13:29:00+05:30
      hee:competitionRatio: 2.56
      hee:discipline: ophthalmology
      hee:duration: 24
      hee:fillRate: 75
      hee:globalRecruitmentFormat: [standard]
      hee:globalRecruitmentFormat__with_ancestors: [standard]
      hee:globalTaxonomyHealthcareTopics: []
      hee:globalTaxonomyHealthcareTopics__with_ancestors: []
      hee:globalTaxonomyProfessions: [dental_professionals, clinical_manager, nurses,
        district_nurse]
      hee:globalTaxonomyProfessions__with_ancestors: [dental_professionals, management_professionals,
        clinical_manager, nurses, district_nurse]
      hee:globalTaxonomyTrainingType: [formal_training]
      hee:globalTaxonomyTrainingType__with_ancestors: [formal_training]
      hee:opening: 2023-09-01T13:29:00+05:30
      hee:professions: []
      hee:recruitmentFormat: standard
      hee:summary: Summary for training programme page
      hee:title: Training Programme Page
      hee:topics: []
      hee:trainingJourneySummary: Training journey summary
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2023-05-30T17:36:34.473+01:00
      hippostdpubwf:lastModificationDate: 2023-08-31T14:22:52.951+01:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2023-08-31T14:22:56.680+01:00
      hippotranslation:id: 0e4f50a9-4101-4078-ba02-437bc48f43df
      hippotranslation:locale: en
      /hee:microHero:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e0a61317-803a-40b0-b1d2-04c53c0c2267
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:logoGroup:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3e62d4df-9ec5-4e03-8ca2-e4f084048900
      /hee:cardImage:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 9bbe1450-f4d7-42a1-b1ac-591010d7429d
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /hee:overview[1]:
        jcr:primaryType: hee:appliesToBoxReference
        /hee:appliesToContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: ec2ddf5d-136e-4006-bc89-c9e1cee4e98f
      /hee:rightHandBlocks[1]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: b68e4b7f-69ca-474f-944c-f8621b9835ed
      /hee:rightHandBlocks[2]:
        jcr:primaryType: hee:contactCardWithDescriptionReference
        /hee:contactCardWithDescription:
          jcr:primaryType: hippo:mirror
          hippo:docbase: a60334fa-81d7-49bc-afc0-a024b6b1a942
      /hee:trainingJourneyOptions:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 3a8eb9c2-5eb6-4be4-9c71-d77bfcc15bbb
      /hee:applicationInformation[1]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /hee:applicationInformation[2]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: c2a82e35-2945-4350-825d-b56c7d46f68d
      /hee:applicationInformation[3]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: f4fb5b81-8054-495f-b1bd-7cf0f0aba641
      /hee:applicationInformation[4]:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 9071bfc1-35e4-4cb8-852c-c91f97fb43f0
      /hee:featuredContentBlock:
        jcr:primaryType: hippo:mirror
        hippo:docbase: 91a74faa-0fb9-4a0c-ac70-ed3becedd670
      /hee:overview[2]:
        jcr:primaryType: hee:detailsReference
        /hee:detailsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: fdf33d93-cb1f-4a12-a954-c5f187e767d2
      /hee:overview[3]:
        jcr:primaryType: hee:expanderGroupReference
        /hee:expanderContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: c6a5f1d2-0b3e-4f0f-bc1a-375146b710fd
      /hee:overview[4]:
        jcr:primaryType: hee:googleMapReference
        /hee:googleMapContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9f09cb7d-5099-4dba-8683-fc453dfdcb16
      /hee:overview[5]:
        jcr:primaryType: hee:tableReference
        /hee:tabledataContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 94afb585-a7a3-4eb9-a2fd-0836aec4d05a
      /hee:overview[6]:
        jcr:primaryType: hee:expanderTableReference
        /hee:expanderTableContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 4c72c1f9-22a7-4819-be39-f1cf1c54e21a
      /hee:overview[7]:
        jcr:primaryType: hee:tabsReference
        /hee:tabsContentBlock:
          jcr:primaryType: hippo:mirror
          hippo:docbase: 9dfce526-0f2e-4b45-a6cd-c0ce59d229bf