/content/documents/lks/trainingprogrammefacets:
  jcr:primaryType: hippofacnav:facetnavigation
  hippo:docbase: 7a39b705-1cac-4076-bc99-726dd5be84e8
  hippofacnav:facets: ['hee:globalTaxonomyTrainingType__with_ancestors', 'hee:globalTaxonomyProfessions__with_ancestors',
    'hee:globalTaxonomyHealthcareTopics__with_ancestors', 'hee:globalTaxonomyClinicalDiscipline__with_ancestors',
    'hee:globalRecruitmentFormat__with_ancestors']
  hippofacnav:filters: ['jcr:primaryType=hee:trainingProgrammePage']
