definitions:
  config:
    /hst:hst/hst:configurations/common/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      /cookies-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.CookiesBannerComponent
        hst:template: base-cookies-banner
      /global-header:
        jcr:primaryType: hst:component
        hst:template: base-global-header
      /announcement-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.BannerComponent
        hst:parameternames: [document, bannerType]
        hst:parametervalues: [settings/banners/announcement-banner, announcement]
        hst:template: base-banner
      /header:
        jcr:primaryType: hst:component
        hst:template: base-header
        /top:
          jcr:primaryType: hst:component
          hst:template: base-top
        /menu:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
          hst:parameternames: [selectedMenu, level, menu]
          hst:parametervalues: ['on', '1', main]
          hst:template: base-menu
      /phase-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.BannerComponent
        hst:parameternames: [document, bannerType]
        hst:parametervalues: [settings/banners/phase-banner, phase]
        hst:template: base-banner
      /breadcrumb:
        jcr:primaryType: hst:component
        hst:template: base-breadcrumb
        hst:componentclassname: uk.nhs.hee.web.components.BreadcrumbComponent
      /mourning-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.BannerComponent
        hst:parameternames: [document, bannerType]
        hst:parametervalues: [settings/banners/mourning-banner, mourning]
        hst:template: base-banner
      /alert-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.BannerComponent
        hst:parameternames: [document, bannerType]
        hst:parametervalues: [settings/banners/alert-banner, alert]
        hst:template: base-banner
      /footer:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', footer]
        hst:template: base-footer
