definitions:
  config:
    /hst:hst/hst:configurations/common/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      /footer:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', footer]
        hst:template: base-footer
      /header:
        jcr:primaryType: hst:component
        hst:template: base-header
        /top:
          jcr:primaryType: hst:component
          hst:template: base-top
        /menu:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
          hst:parameternames: [selectedMenu, level, menu]
          hst:parametervalues: ['on', '1', main]
          hst:template: base-menu
      /breadcrumb:
        jcr:primaryType: hst:component
        hst:template: base-breadcrumb
        hst:componentclassname: uk.nhs.hee.web.components.BreadcrumbComponent
      /banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.BannerComponent
        hst:template: base-banner
        hst:parameternames: [document]
        hst:parametervalues: [site-banner]
      /cookies-banner:
        jcr:primaryType: hst:component
        hst:componentclassname: uk.nhs.hee.web.components.CookiesBannerComponent
        hst:template: base-cookies-banner
