definitions:
  config:
    /hippo:configuration/hippo:workflows/default/authorHandle:
      .meta:order-before: handle
      jcr:primaryType: frontend:workflow
      hipposys:classname: uk.nhs.hee.web.repository.documentworkflow.AuthorDocumentWorkflowImpl
      hipposys:display: Author handle workflow
      hipposys:nodetype: hippo:handle
      hipposys:privileges: ['hippo:author']
      hipposys:subtype: hee:author
      /hipposys:config:
        jcr:primaryType: nt:unstructured
        scxml-definition: documentworkflow
      /frontend:renderer:
        jcr:primaryType: frontend:plugincluster
        frontend:references: [browser.id, editor.id, wicket.model]
        frontend:services: [wicket.id]
        item: ${cluster.id}.item
        /root:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
        /admin:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.AdminWorkflowPlugin
          wicket.id: ${item}
        /publication:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.PublicationWorkflowPlugin
          wicket.id: ${item}
        /document:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.DocumentWorkflowPlugin
          wicket.id: ${item}
        /top:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.PreviewWorkflowPlugin
          wicket.id: ${item}
        /requests:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.RequestsWorkflowPlugin
          wicket.id: ${item}
        /metadata:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.reviewedactions.DocMetaDataPlugin
          wicket.id: ${item}
        /channelactions:
          jcr:primaryType: frontend:plugin
          plugin.class: org.onehippo.cms7.channelmanager.plugins.channelactions.ChannelActionsPlugin
          wicket.id: ${item}
