definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
          /pagenotfound:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:pagetitle: Page not found
            hst:refId: pagenotfound
          /_any_:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/pagenotfound
            hst:pagetitle: Page not found
          /root:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/homepage
            hst:pagetitle: Home
            hst:refId: root
            hst:relativecontentpath: home
          /search:
            jcr:primaryType: hst:sitemapitem
            hst:hiddeninchannelmanager: true
            hst:parameternames: [excludedForBreadcrumb]
            hst:parametervalues: ['true']
            hst:refId: search
            /results:
              jcr:primaryType: hst:sitemapitem
              hst:componentconfigurationid: hst:pages/searchresults
              hst:pagetitle: Search
              hst:relativecontentpath: listing-pages/search-results
          /cookies:
            jcr:primaryType: hst:sitemapitem
            hst:componentconfigurationid: hst:pages/cookies
            hst:pagetitle: Cookies
            hst:refId: cookies
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-footer.ftl
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-layout.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/pagenotfound-main.ftl
          /base-header:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-header.ftl
          /base-top:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-top.ftl
          /base-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-menu.ftl
          /guidance-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/guidance-main.ftl
          /landingpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/landingPage-main.ftl
          /base-breadcrumb:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-breadcrumb.ftl
          /minihub-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/minihub-main.ftl
          /formpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/formpage-main.ftl
          /blogpost-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/blogpost-main.ftl
          /searchresults-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/searchresults-main.ftl
          /categorybasedlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/categorybasedlisting-main.ftl
          /eventlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/eventlisting-main.ftl
          /casestudylisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/casestudylisting-main.ftl
          /searchbanklisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/searchbanklisting-main.ftl
          /cookies-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/cookies-main.ftl
          /base-banner:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-banner.ftl
          /news-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/news-main.ftl
          /multi-org-logo:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/multi-org-logo.ftl
          /base-cookies-banner:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-cookies-banner.ftl
          /atozlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/atozlisting-main.ftl
          /report-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/report-main.ftl
          /publicationlandingpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/publicationlandingpage-main.ftl
          /trainingprogrammeshomepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl
          /trainingprogrammepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/trainingProgrammePage-main.ftl
          /taxonomybasedlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/taxonomybasedlisting-main.ftl
          /notfoundpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/notFoundPage-main.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /common-catalog:
            jcr:primaryType: hst:containeritempackage
            /guidance:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.GuidanceComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Standard Content Page
              hst:template: guidance-main
            /landingpage:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.LandingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Landing Page
              hst:template: landingpage-main
            /minihub:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.MiniHubComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: MiniHub
              hst:template: minihub-main
            /category-based-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.CategoryBasedListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: Bulletin listing page
              hst:template: categorybasedlisting-main
            /blogpost:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.BlogPostComponent
              hst:template: blogpost-main
              hst:label: BlogPost
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
            /event-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.EventListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: Event Listing Page
              hst:template: eventlisting-main
            /case-study-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.CaseStudyListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: Case Study Listing Page
              hst:template: casestudylisting-main
            /search-bank-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.SearchBankListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: Search Bank Listing Page
              hst:template: searchbanklisting-main
            /news:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.NewsComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: News
              hst:template: news-main
            /multi-org-logo:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.MultiOrgLogoComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/carousel.svg
              hst:label: Multi org logo
              hst:template: multi-org-logo
            /a-to-z-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.AToZListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: A to Z Listing Page
              hst:template: atozlisting-main
            /report:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.ReportComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Publication page
              hst:template: report-main
            /publication-landing-page:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.PublicationLandingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Publication Landing Page
              hst:template: publicationlandingpage-main
            /taxonomy-based-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.TaxonomyBasedListingPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/generic-list.svg
              hst:label: Taxonomy-based collection pages [blog, news & publication]
              hst:template: taxonomybasedlisting-main
            /trainingprogrammes-homepage:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.TrainingProgrammesHomepageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Training Programmes Homepage
              hst:template: trainingprogrammeshomepage-main
            /trainingprogramme-page:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.TrainingProgrammePageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Training Programme Page
              hst:template: trainingprogrammepage-main
            /notfound-page:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.NotFoundPageComponent
              hst:iconpath: _cmsinternal/images/catalog-component-icons/simple-content.svg
              hst:label: Not Found Page
              hst:template: notfoundpage-main
      /lks:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /digital-transformation:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /dental:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /medical:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /health-careers:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /quality:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /website-testing:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /kls:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /wte-alpha:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /feedback:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
