definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-footer.ftl
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-layout.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/pagenotfound-main.ftl
          /base-header:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-header.ftl
          /base-top:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-top.ftl
          /base-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-menu.ftl
          /guidance-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/guidance-main.ftl
          /listingpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/listingpage-main.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /common-catalog:
            jcr:primaryType: hst:containeritempackage
            /guidance:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.GuidanceComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: Guidance
              hst:template: guidance-main
            /lisingpage:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.ListingPageComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: Listing Page
              hst:template: listingpage-main
      /lks:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
