definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-footer.ftl
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-layout.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/pagenotfound-main.ftl
          /base-header:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-header.ftl
          /base-top:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-top.ftl
          /base-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-menu.ftl
          /guidance-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/guidance-main.ftl
          /landingpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/landingPage-main.ftl
          /base-breadcrumb:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-breadcrumb.ftl
          /base-parent-link:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/base-parent-link.ftl
          /minihub-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/minihub-main.ftl
          /formpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/formpage-main.ftl
          /afterform-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/afterform-main.ftl
          /hero-section:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/layout/hero-section.ftl
          /blogpost-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/blogpost-main.ftl
          /searchresults-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/searchresults-main.ftl
          /categorybasedlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/categorybasedlisting-main.ftl
          /blogpage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/pages/blogpage-main.ftl
          /eventlisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/eventlisting-main.ftl
          /casestudylisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/casestudylisting-main.ftl
          /searchbanklisting-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hee/catalog/searchbanklisting-main.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /common-catalog:
            jcr:primaryType: hst:containeritempackage
            /guidance:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.GuidanceComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: Guidance
              hst:template: guidance-main
            /landingpage:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.LandingPageComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: Landing Page
              hst:template: landingpage-main
            /minihub:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.MiniHubComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: MiniHub
              hst:template: minihub-main
            /after-form:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsDocumentComponent
              hst:iconpath: images/catalog-component-icons/simple-content.svg
              hst:label: AfterForm
              hst:template: afterform-main
            /category-based-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.CategoryBasedListingPageComponent
              hst:iconpath: images/catalog-component-icons/generic-list.svg
              hst:label: Category based Listing Page [Bulletin & Blog]
              hst:template: categorybasedlisting-main
            /blogpost:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.BlogPostComponent
              hst:template: blogpost-main
              hst:label: BlogPost
              hst:iconpath: images/catalog-component-icons/simple-content.svg
            /event-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.EventListingPageComponent
              hst:iconpath: images/catalog-component-icons/generic-list.svg
              hst:label: Event Listing Page
              hst:template: eventlisting-main
            /case-study-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.CaseStudyListingPageComponent
              hst:iconpath: images/catalog-component-icons/generic-list.svg
              hst:label: Case Study Listing Page
              hst:template: casestudylisting-main
            /search-bank-listing:
              jcr:primaryType: hst:containeritemcomponent
              hst:componentclassname: uk.nhs.hee.web.components.SearchBankListingPageComponent
              hst:iconpath: images/catalog-component-icons/generic-list.svg
              hst:label: Search Bank Listing Page
              hst:template: searchbanklisting-main
      /lks:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
