definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        hst:responseheaders: ['Content-Security-Policy: frame-ancestors ''self''',
          'X-Frame-Options: SAMEORIGIN']
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:hee/hst:sites/lks
          hst:locale: en
          /digital-transformation:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:hee/hst:sites/digital-transformation
          /dental:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:hee/hst:sites/dental
          /medical:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:hee/hst:sites/medical
          /website-testing:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:hee/hst:sites/website-testing
