package uk.nhs.hee.web.repository;

/**
 * Provides an enumeration of HEE Fields/Properties.
 */
public enum HEEField {

    /**
     * {@code categories} field/property.
     */
    CATEGORIES("hee:categories"),

    /**
     * {@code completedDate} field/property.
     */
    COMPLETED_DATE("hee:completedDate"),

    /**
     * {@code date} field/property.
     */
    DATE("hee:date"),

    /**
     * {@code title} field/property.
     */
    DOCUMENT_TITLE("hee:title"),

    /**
     * {@code impactGroup} field/property.
     */
    IMPACT_GROUP("hee:impactGroup"),

    /**
     * {@code listingPageType} field/property.
     */
    LISTING_TYPE("hee:listingPageType"),

    /**
     * {@code publicationDate} field/property.
     */
    PUBLICATION_DATE("hee:publicationDate"),

    /**
     * {@code globalTaxonomyPublicationType} taxonomy field/property.
     */
    HEE_GLOBAL_TAXONOMY_PUBLICATION_TYPE("hee:globalTaxonomyPublicationType"),

    /**
     * {@code globalTaxonomyPublicationType__with_ancestors} taxonomy field/property.
     *
     * <p>An alternate version of {@code globalTaxonomyPublicationType} taxonomy field with ancestors
     * and is generated by brXM out-of-the-box.</p>
     */
    HEE_GLOBAL_TAXONOMY_PUBLICATION_TYPE_WITH_ANCESTORS("hee:globalTaxonomyPublicationType__with_ancestors"),

    /**
     * {@code globalTaxonomyHealthcareTopics} taxonomy field/property.
     */
    HEE_GLOBAL_TAXONOMY_HEALTHCARE_TOPICS("hee:globalTaxonomyHealthcareTopics"),

    /**
     * {@code globalTaxonomyHealthcareTopics__with_ancestors} taxonomy field/property.
     *
     * <p>An alternate version of {@code globalTaxonomyHealthcareTopics} taxonomy field with ancestors
     * and is generated by brXM out-of-the-box.</p>
     */
    HEE_GLOBAL_TAXONOMY_HEALTHCARE_TOPICS_WITH_ANCESTORS("hee:globalTaxonomyHealthcareTopics__with_ancestors"),

    /**
     * {@code globalTaxonomyProfessions} taxonomy field/property.
     */
    HEE_GLOBAL_TAXONOMY_PROFESSIONS("hee:globalTaxonomyProfessions"),

    /**
     * {@code globalTaxonomyProfessions__with_ancestors} taxonomy field/property.
     *
     * <p>An alternate version of {@code globalTaxonomyProfessions} taxonomy field with ancestors
     * and is generated by brXM out-of-the-box.</p>
     */
    HEE_GLOBAL_TAXONOMY_PROFESSIONS_WITH_ANCESTORS("hee:globalTaxonomyProfessions__with_ancestors"),

    /**
     * {@code topics} field/property.
     */
    TOPICS("hee:topics"),

    /**
     * {@code submittedDate} field/property.
     */
    SUBMITTED_DATE("hee:submittedDate");

    private final String name;

    /**
     * Constructor that initialises the name of HEE fields/properties.
     *
     * @param name the name of HEE fields/properties.
     */
    HEEField(final String name) {
        this.name = name;
    }

    /**
     * Returns the name of HEE field/property.
     *
     * @return the name of HEE field/property.
     */
    public String getName() {
        return this.name;
    }
}
