/content/documents/feedback/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 92637c26-1a1a-478f-8a44-3f297fee1925
  hippo:name: Settings
  hippostd:foldertype: [new-folder]
  hippotranslation:id: e79b221d-68ea-4866-9186-0cb46c67baf9
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: 6c1bd94b-415b-4515-a3dd-4d0ce7461d37
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 96b873e9-c0a6-4675-ba3b-06c8793ae695
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 436c7016-06ef-44f9-b172-4df5632c9250
    hippotranslation:locale: en
