/hst:hst/hst:configurations/lks/hst:workspace/hst:sitemap/training-program-collection:
  jcr:primaryType: hst:sitemapitem
  hst:componentconfigurationid: hst:pages/training-program-collection-contentpage
  hst:lastmodified: 2023-09-20T16:44:50.953+01:00
  hst:pagetitle: Training Program Collection
  /training-home:
    jcr:primaryType: hst:sitemapitem
    hst:componentconfigurationid: hst:pages/training-home-contentpage
    hst:lastmodified: 2023-09-20T16:44:27.647+01:00
    hst:pagetitle: training-home
  /training-programme-page:
    jcr:primaryType: hst:sitemapitem
    hst:componentconfigurationid: hst:pages/training-programme-page-training-programme-page
    hst:lastmodified: 2023-09-20T16:44:50.953+01:00
    hst:pagetitle: Training Programme Page
    /_default_:
      jcr:primaryType: hst:sitemapitem
      hst:componentconfigurationid: hst:pages/training-programme-page-training-programme-page
      hst:pagetitle: Training Programme Page
