/content/documents/wte-alpha/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 1e312eaa-1b45-4ff6-aa9b-72dad67c0905
  hippo:name: Settings
  hippostd:foldertype: [new-folder]
  hippotranslation:id: e79b221d-68ea-4866-9186-0cb46c67baf9
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: 8bbce363-4ac3-4fe9-b5b7-6cf88351938b
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 16a279c8-46a8-4ea0-8e15-4631cc14b22e
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: ef863b44-51a2-465f-bf86-1ad0fd5ced20
    hippotranslation:locale: en
