/content/documents/kls/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 0495661f-581e-4d76-a52d-e6e8e5951b2d
  hippo:name: Settings
  hippostd:foldertype: [new-folder]
  hippotranslation:id: e79b221d-68ea-4866-9186-0cb46c67baf9
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: 5f572ff1-60cf-4437-a6ee-13431b2775cd
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: b6a3c4d6-5e45-4eca-95e0-133c088c0303
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 366fabc8-b296-4742-998c-cbc19e2d95cd
    hippotranslation:locale: en
