/content/documents/digital-transformation/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 7ea8f99a-b63f-408a-ab34-cfad7ffc560f
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: 0208e127-386f-42f6-8baa-97145ebd27c7
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: b9322a93-4c4a-4e26-b794-8fafd6e17a26
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 8b8912e4-3270-43f0-96b5-0a71bb6e66ae
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: bdbf3e24-c34d-4a92-ada8-f0e37114eab0
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: adb12464-29e6-4c35-911c-70a01bbe4edb
    hippotranslation:locale: en
