/content/documents/administration/lks/lksconfiguration:
  jcr:primaryType: hippo:handle
  jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
  jcr:uuid: 6d4aead0-6a92-44c4-8f0b-d108fec4e95f
  hippo:name: LKSConfiguration
  hippo:versionHistory: 87c766f2-5823-435a-a3bf-2fb14c5d4911
  /lksconfiguration[1]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: cd4e2989-e7bb-482b-b113-c662c975b436
    hippo:availability: []
    hippostd:retainable: false
    hippostd:state: draft
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-03-31T08:40:55.201+01:00
    hippostdpubwf:lastModificationDate: 2021-03-31T13:55:53.083+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: ['']
    resourcebundle:id: uk.nhs.hee.web.lks.configuration
    resourcebundle:keys: [blog.overview]
    resourcebundle:messages: [/blogs]
  /lksconfiguration[2]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
    jcr:uuid: 789ca3d9-ca4d-4eea-994f-a7c72ac96be9
    hippo:availability: [preview]
    hippostd:retainable: false
    hippostd:state: unpublished
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-03-31T08:40:55.201+01:00
    hippostdpubwf:lastModificationDate: 2021-03-31T13:55:52.955+01:00
    hippostdpubwf:lastModifiedBy: admin
    resourcebundle:descriptions: ['']
    resourcebundle:id: uk.nhs.hee.web.lks.configuration
    resourcebundle:keys: [blog.overview]
    resourcebundle:messages: [/blogs]
  /lksconfiguration[3]:
    jcr:primaryType: resourcebundle:resourcebundle
    jcr:mixinTypes: ['mix:referenceable']
    jcr:uuid: f60da74b-7628-4348-94bb-915aa9e204ef
    hippo:availability: [live]
    hippostd:retainable: false
    hippostd:state: published
    hippostdpubwf:createdBy: admin
    hippostdpubwf:creationDate: 2021-03-31T08:40:55.201+01:00
    hippostdpubwf:lastModificationDate: 2021-03-31T13:55:52.955+01:00
    hippostdpubwf:lastModifiedBy: admin
    hippostdpubwf:publicationDate: 2021-03-31T13:55:56.130+01:00
    resourcebundle:descriptions: ['']
    resourcebundle:id: uk.nhs.hee.web.lks.configuration
    resourcebundle:keys: [blog.overview]
    resourcebundle:messages: [/blogs]
