/content/documents/dental/settings:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: a8a4541e-de26-47a0-ad05-19a521a711d2
  hippo:name: Settings
  hippostd:foldertype: [new-translated-folder]
  hippotranslation:id: 61829fef-7b29-4f23-b783-ad2ead3e5523
  hippotranslation:locale: en
  /banners:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 8c2fef9d-bc88-4744-b960-e80d840b23b8
    hippo:name: Banners
    hippostd:foldertype: [new-banner-document]
    hippotranslation:id: 5a0d44fc-ce45-4b32-9936-242cd1a56ecd
    hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 15cbb1a3-7c67-4380-99fe-b895ab25ba58
    hippo:name: Pages
    hippostd:foldertype: [new-landing-document]
    hippotranslation:id: 9a817e9b-4304-4a17-bb6c-8ff7b3516026
    hippotranslation:locale: en
