/content/documents/main/local:
  .meta:order-before: custom-folder
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 5c9feb79-0f99-4fbd-936d-6eaa35f2d815
  hippo:name: Local
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: 6dee2473-9517-4950-b495-22eb7b06555b
  hippotranslation:locale: en
  /pages:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 7976c099-d012-4536-a1d6-223b9a05e49e
    hippo:name: Pages
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: c73ad5b2-d439-4f23-af45-549d08539e6a
    hippotranslation:locale: en
  /components:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
    jcr:uuid: 0319fdbb-bb07-45d1-99fb-0a39a6c11e6b
    hippo:name: Components
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: a1928400-6d19-4d9a-a7c2-74b54745add5
    hippotranslation:locale: en
