name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      BLOOMREACH_MVN_USERNAME: ${{ secrets.BLOOMREACH_MVN_USERNAME }}
      BLOOMREACH_MVN_PASSWORD: ${{ secrets.BLOOMREACH_MVN_PASSWORD }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Set up JDK 17 with Maven auth
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
          server-id: bloomreach-maven2-enterprise
          server-username: BLOOMREACH_MVN_USERNAME
          server-password: BLOOMREACH_MVN_PASSWORD

      - name: Compile
        run: mvn -B clean compile -Pdefault --file pom.xml

      - name: Test
        run: mvn -B clean test -Pdefault --file pom.xml