name: update-test-prototype-branch
on: 
  push:
    branches:
      - 'NWPS-876-front-end-prototype-tidy-up' 
env:
  BRC_STACK_NAME: hee
  # BRC_MAX_DISTRIBUTIONS: 90
  BRC_DISTRIBUTION_DELETE_COUNT: 10

jobs:
  if: github.ref == 'refs/heads/NWPS-876-front-end-prototype-tidy-up'
  deploy-to-test:
    name: Deploy to Test Env. [on brCloud]
    if: ${{ github.ref == 'refs/heads/NWPS-876-front-end-prototype-tidy-up' }}
    needs: buildAndTest
    environment: test

    env:
      BRC_ENV_NAME: test

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo.
        uses: actions/checkout@v3
        with:
          ref: 'NWPS-876-front-end-prototype-tidy-up'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure maven settings
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "hippo-maven2-enterprise", "url": "https://maven.onehippo.com/maven2-enterprise/" }]'
          plugin_repositories: '[{ "id": "hippo-maven2-enterprise", "url": "https://maven.onehippo.com/maven2-enterprise/" }]'
          servers: '[{ "id": "hippo-maven2-enterprise", "username": "${{ secrets.BLOOMREACH_MVN_USERNAME }}", "password": "${{ secrets.BLOOMREACH_MVN_PASSWORD }}" }]'

      - name: Package
        run: mvn -B verify && mvn -Pdist -Denv=${{ env.BRC_ENV_NAME }} --file pom.xml

      - name: Setting distribution path (distPath) as an output parameter
        id: dist
        run: echo "::set-output name=distPath::$(ls -1 ${{ github.workspace }}/target/$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)-$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-$(git rev-parse --short "$GITHUB_SHA")-${{ env.BRC_ENV_NAME }}-*.tar.gz)"

      - name: Clean up/delete distributions when Bloomreach Cloud hits maximum distributions
        uses: Health-Education-England/cleanup-distributions-from-BR-Cloud-action@v1.1
        id: cleanup
        with:
          brcStack: ${{ env.BRC_STACK_NAME }}
          username: ${{ secrets.BRC_USERNAME }}
          password: ${{ secrets.BRC_PASSWORD }}
          # maxDistributions: ${{ env.BRC_MAX_DISTRIBUTIONS }}
          distributionsDeleteCount: ${{ env.BRC_DISTRIBUTION_DELETE_COUNT }}
      - name: Upload distribution to Bloomreach Cloud
        uses: Health-Education-England/upload-distribution-to-BR-Cloud-action@v1.1
        id: upload
        with:
          brcStack: ${{ env.BRC_STACK_NAME }}
          username: ${{ secrets.BRC_USERNAME }}
          password: ${{ secrets.BRC_PASSWORD }}
          distPath: ${{ steps.dist.outputs.distPath }}
      - name: Deploy distribution to 'test' env
        uses: Health-Education-England/deploy-distribution-to-BR-Cloud-action@v1.2
        id: deploy
        with:
          brcStack: ${{ env.BRC_STACK_NAME }}
          username: ${{ secrets.BRC_USERNAME }}
          password: ${{ secrets.BRC_PASSWORD }}
          distId: ${{ steps.upload.outputs.distId }}
          envName: ${{ env.BRC_ENV_NAME }}
          configFilesAsSystemProperties: 'hee-smtp.properties'


